kind: CredentialProviderConfig
apiVersion: kubelet.config.k8s.io/v1
providers:
- name: credential-provider-echo-token-silly
  apiVersion: credentialprovider.kubelet.k8s.io/v1
  tokenAttributes:
    requireServiceAccount: true
    serviceAccountTokenAudience: "my-registry"
    cacheType: Token
  matchImages:
  - "silly-snyder.container-registry.com"
  defaultCacheDuration: "1h"

  # optionally specify the username to include in registry credentials, default is "" if unset
  # args:
  # - "--username="
